apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qpl9vzksr-python 
  janus-idp.io/tekton: qpl9vzksr-python
  backstage.io/kubernetes-id: qpl9vzksr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qpl9vzksr-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  